CREATE TABLE chat_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id VARCHAR(64) NOT NULL,
  lang VARCHAR(5) NOT NULL,
  email VARCHAR(255) NULL,
  transcript TEXT NOT NULL,
  meeting_booked TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_conversation_id (conversation_id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
